name: "Bedwars"
description: "Bedwars Plugin for Pocketmine"
version: 2.1
api: [5.0.0]
authors:
  - Fludixx
  - xxFLORII
main: Fludixx\Bedwars\Bedwars
permissions:
  bw.admin:
    description: "Allows the Owner of the Permission to manage Bedwars Arenas"
    default: op
  bw.build:
    description: "Allows the Owner of the Permission to use /bwbuild"
    default: op